### PR TITLE
Refactor: Add Google Fonts section from vanilla JS to React app

### PR DESCRIPTION
**Pull request by matiasbenedetto**
This PR refactors the "Add Google Fonts" section of the plugin. It moves the implementation from Vanilla JS to React.
This enables further improvements to the app with less effort and more code reusability.

### CODE REVIEW

**Review by mikachan — COMMENTED** [review]
Great refactoring work!

When I build this, I'm seeing a webpack warning about the size of the output index.js file:

```
WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets:
  index.js (868 KiB)
```

Should we split this up into multiple JS files now, or maybe we could do it in a separate PR?

**Comment by matiasbenedetto** [comment]
Thanks for catching that @mikachan !
I think we can try to implement the code splitting as a part of another PR because it's not related to this refactor or this set of changes.

**Review by mikachan — APPROVED** [review]
> I think we can try to implement the code splitting as a part of another PR because it's not related to this refactor or this set of changes.

Sounds good to me! I think this is good to merge in then 🚢

**Comment by matiasbenedetto** [comment]
I created an issue as a follow up of the bundle size: https://github.com/WordPress/create-block-theme/issues/205

**Pull request merged**
