### PR TITLE
Fixing readme contributors

### LINKED ISSUE #125: Readme.txt: Fix several issues with contributors list
I recently ran into an issue where Create Block Theme was not showing in the `wordpressdotorg` user's list of plugins.

Please see this meta ticket for details:

https://meta.trac.wordpress.org/ticket/6539

In exploring the cause, it turns out that there are a couple of issues in the Create Block Theme's readme:

1 - "Author" is not a valid readme field and should be removed entirely:

`Author: @wordpressdotorg`

2 - Usernames in readme files should not include the @ so they should be removed here:

`Contributors: @chaosexanima, @mikachan, @onemaggie, @pbking, @scruffian`

3 - `chaosexanima` is not a WordPress.org username: https://profiles.wordpress.org/chaosexanima/ It should either be swapped out for the correct WP.org username, or removed.

4 -  The `wordpressdotorg` user should be added first to the list of contributors

Thanks for having a look when you're able!

### PR DESCRIPTION
**Pull request by matiasbenedetto**
fixing readme contributors as requested in #125

Fixes: #125

### CODE REVIEW

**Comment by kathrynwp** [comment]
Thank you, @matiasbenedetto! Looks good except the `@` still needs to be removed in this line:

`Contributors: @wordpressdotorg, mikachan, onemaggie, pbking, scruffian, mmaattiiaass, jffng, madhudollu`

**Comment by matiasbenedetto** [comment]
done! thanks @kathrynw! If the change looks good please approve the PR.

**Review by kathrynwp — APPROVED** [review]
lgtm

**Comment by kathrynwp** [comment]
@matiasbenedetto Was my first time approving a PR, so just let me know if I need to do anything else, thanks!

**Comment by matiasbenedetto** [comment]
Nothing else is required! thanks @kathrynwp!

**Pull request merged**
