### PR TITLE
Move lib-font and add GPL license text to source files

### PR DESCRIPTION
**Pull request by matiasbenedetto**
## What?
Move lib-font and add GPL license text to source files.

## Why?
- We need to add the license text of the libs bundled in source code.
- This is part of the effort to re-introduce the font license theme automation (https://github.com/WordPress/create-block-theme/issues/525).

### CODE REVIEW

**Review by pbking — APPROVED** [review]
Looks fine to me

🚢

**Comment by vcanales** [comment]
@matiasbenedetto Are we actually using lib-font? What about unbrotli? Actually... are we using any of these?

**Comment by matiasbenedetto** [comment]
Yes, lib-font is used to read fonts metadata to extract font license info. Unbrotli nad inflate files contain the functions used by Lib-font to uncompress the fonts in compressed formats as .woff and .woff2.

**Comment by vcanales** [comment]
I see. It's part of something that is not merged yet (https://github.com/WordPress/create-block-theme/pull/649)

**Pull request merged**
