### PR TITLE
Local fonts section implementation in React

### PR DESCRIPTION
**Pull request by matiasbenedetto**
## What?
In this PR:
- Implement the local font asset upload in the React App
- Change the styles of this section to make it lool as the rest of the font section as implemented in https://github.com/WordPress/create-block-theme/pull/260

## Why?
To allow us to implement the user ability to add more configuration options.

## How to test:
- Go to the "Add local font" page
- Add a few fonts a test if everything is working as before.

## Extra info:

:warning: This PR has as base the branch of https://github.com/WordPress/create-block-theme/pull/260 to re-use some of the components implemented in that branch.
Before merging it we need to use trunk as base.

### CODE REVIEW

**Comment by madhusudhand** [comment]
Can you point the PR to trunk?

**Comment by matiasbenedetto** [comment]
> Can you point the PR to trunk?

If I do that all the changes from `add/fonts-sidebar` will show in the diff. What would you want to do that?

**Comment by madhusudhand** [comment]
> If I do that all the changes from add/fonts-sidebar will show in the diff. What would you want to do that?

No. It adds more noise.

I would like this to be independent with related changes so it would be easy to review and merge.
If you think it has to depend on the changes from #260, let's mark this as draft PR for time being.

**Comment by matiasbenedetto** [comment]
I'm closing this PR in favor of this other one that can be merged independently of other code changes:  https://github.com/WordPress/create-block-theme/pull/268

**Pull request closed without merging**
